version: '2.0'

services:
  'counter':
    container_name: counter
    hostname: counter
    image: counter:latest
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    env_file:
      - .env
  'redis':
    image: "redis:alpine"
    hostname: redis
    container_name: redis
